version: '3.5'
services:
  web: 
    image: nginx:latest
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./website/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./website/src:/var/www/html
    networks:
      ct_net: {}
  php:
    build: ./php-fpm
    restart: always
    volumes:
      - ./website/src:/var/www/html
    networks:
      ct_net: {}
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_DATABASE: "checker_db"
    restart: always
    volumes:
      - ./database/mapped:/var/lib/mysql
      - ./database/conf/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./website/src:/var/www/html:ro
    networks:
      ct_net: {}

networks:
  ct_net: 
    driver: overlay
    name: ct_net
